/**
 * Comprehensive PDF Summary Generator
 * Generates professional PDF summaries (not quotes) for Depot Voice Notes sessions
 * Includes system analysis, recommendations, technical specs, warranty, pricing, and finance options
 */

/**
 * Load image as base64 for embedding in PDF
 */
async function loadImageAsBase64(imagePath) {
  try {
    const response = await fetch(imagePath);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error(`Failed to load image: ${imagePath}`, error);
    return null;
  }
}

/**
 * Add text with word wrap
 */
function addWrappedText(doc, text, x, y, maxWidth, lineHeight = 6) {
  const lines = doc.splitTextToSize(text, maxWidth);
  let currentY = y;

  lines.forEach(line => {
    doc.text(line, x, currentY);
    currentY += lineHeight;
  });

  return currentY;
}

/**
 * Check if we need a new page
 */
function checkPageBreak(doc, yPos, neededSpace = 40, margin = 15) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (yPos > pageHeight - neededSpace) {
    doc.addPage();
    return margin + 10; // Return to top of new page with header space
  }
  return yPos;
}

/**
 * Add page header with purple gradient
 */
function addPageHeader(doc, title, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Purple gradient background
  doc.setFillColor(102, 126, 234); // #667eea
  doc.rect(0, 0, pageWidth, 25, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text(title, 15, 16);

  // Page number
  if (pageNum && totalPages) {
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 35, 16);
  }

  doc.setTextColor(0, 0, 0); // Reset to black
}

/**
 * Add footer with disclaimer
 */
function addPageFooter(doc, pageNum) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text(
    'This document is for informational purposes only and does not constitute a formal quotation or contract.',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );
  doc.text(
    `Generated by Depot Voice Notes - ${new Date().toLocaleString('en-GB')} - Page ${pageNum}`,
    pageWidth / 2,
    pageHeight - 5,
    { align: 'center' }
  );
}

/**
 * Generate cover page
 */
async function generateCoverPage(doc, summaryData) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Full page purple gradient background
  doc.setFillColor(102, 126, 234); // #667eea
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Main title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont(undefined, 'bold');
  doc.text('Heating System', pageWidth / 2, 70, { align: 'center' });
  doc.text('Summary Report', pageWidth / 2, 92, { align: 'center' });

  // Subtitle
  doc.setFontSize(16);
  doc.setFont(undefined, 'normal');
  doc.text('Information & Recommendations', pageWidth / 2, 110, { align: 'center' });

  // Session info box
  const boxY = 130;
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(30, boxY, pageWidth - 60, 80, 5, 5, 'F');

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.text('Session Information', pageWidth / 2, boxY + 15, { align: 'center' });

  doc.setFont(undefined, 'normal');
  doc.setFontSize(10);
  let infoY = boxY + 28;

  if (summaryData.sessionName) {
    doc.setFont(undefined, 'bold');
    doc.text('Session:', 40, infoY);
    doc.setFont(undefined, 'normal');
    doc.text(summaryData.sessionName, 75, infoY);
    infoY += 8;
  }

  if (summaryData.sessionDate) {
    doc.setFont(undefined, 'bold');
    doc.text('Date:', 40, infoY);
    doc.setFont(undefined, 'normal');
    doc.text(summaryData.sessionDate, 75, infoY);
    infoY += 8;
  }

  if (summaryData.what3words) {
    doc.setFont(undefined, 'bold');
    doc.text('Location:', 40, infoY);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(102, 126, 234);
    doc.text(`///${summaryData.what3words}`, 75, infoY);
    doc.setTextColor(0, 0, 0);
    infoY += 8;
  }

  if (summaryData.customerName) {
    doc.setFont(undefined, 'bold');
    doc.text('Customer:', 40, infoY);
    doc.setFont(undefined, 'normal');
    doc.text(summaryData.customerName, 75, infoY);
    infoY += 8;
  }

  if (summaryData.propertyType) {
    doc.setFont(undefined, 'bold');
    doc.text('Property:', 40, infoY);
    doc.setFont(undefined, 'normal');
    doc.text(summaryData.propertyType, 75, infoY);
  }

  // Disclaimer box
  const disclaimerY = 225;
  doc.setFillColor(255, 243, 199); // Light yellow
  doc.roundedRect(30, disclaimerY, pageWidth - 60, 35, 5, 5, 'F');

  doc.setTextColor(146, 64, 14);
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('⚠️  Important Notice', pageWidth / 2, disclaimerY + 12, { align: 'center' });

  doc.setFont(undefined, 'normal');
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);
  const disclaimerText = 'This document is for informational purposes only. It does not constitute a formal quotation, contract, or guarantee. All recommendations, pricing, and technical specifications are subject to site survey and final confirmation.';
  const disclaimerLines = doc.splitTextToSize(disclaimerText, pageWidth - 80);
  let disclaimerTextY = disclaimerY + 20;
  disclaimerLines.forEach(line => {
    doc.text(line, pageWidth / 2, disclaimerTextY, { align: 'center' });
    disclaimerTextY += 4;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('Powered by Depot Voice Notes', pageWidth / 2, pageHeight - 15, { align: 'center' });
}

/**
 * Generate existing system analysis page
 */
async function generateExistingSystemPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Existing System Analysis', pageNum, totalPages);

  let yPos = 35;

  // Extract existing system info from sections
  const existingSections = summaryData.sections.filter(s =>
    s.title.toLowerCase().includes('system') ||
    s.title.toLowerCase().includes('existing') ||
    s.title.toLowerCase().includes('current')
  );

  if (existingSections.length > 0) {
    existingSections.forEach(section => {
      yPos = checkPageBreak(doc, yPos, 50, margin);

      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(102, 126, 234);
      doc.text(section.title, margin, yPos);
      yPos += 8;

      doc.setFontSize(9);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(0, 0, 0);
      yPos = addWrappedText(doc, section.content, margin, yPos, contentWidth, 5);
      yPos += 10;
    });
  } else {
    // Fallback if no specific sections found
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text('Current system details captured during site visit.', margin, yPos);
    yPos += 10;
  }

  // Add any identified issues
  if (summaryData.issues && summaryData.issues.length > 0) {
    yPos = checkPageBreak(doc, yPos, 60, margin);

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(239, 68, 68); // Red
    doc.text('⚠ Identified Issues', margin, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(0, 0, 0);

    summaryData.issues.forEach(issue => {
      yPos = checkPageBreak(doc, yPos, 20, margin);
      yPos = addWrappedText(doc, `• ${issue}`, margin + 3, yPos, contentWidth - 3, 5);
      yPos += 3;
    });
  }

  addPageFooter(doc, pageNum);
}

/**
 * Generate proposed system page
 */
async function generateProposedSystemPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Proposed New System', pageNum, totalPages);

  let yPos = 35;

  // Extract proposed system from AI notes
  const aiNotesText = summaryData.aiNotes || '';

  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(16, 185, 129); // Green
  doc.text('✓ Recommended Solution', margin, yPos);
  yPos += 10;

  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);

  if (aiNotesText) {
    yPos = addWrappedText(doc, aiNotesText, margin, yPos, contentWidth, 5);
  } else {
    doc.text('System recommendations based on site assessment and customer requirements.', margin, yPos);
  }

  yPos += 15;

  // Key benefits section
  yPos = checkPageBreak(doc, yPos, 60, margin);

  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(102, 126, 234);
  doc.text('Key Benefits', margin, yPos);
  yPos += 8;

  const benefits = summaryData.benefits || [
    'Improved energy efficiency',
    'Enhanced comfort and control',
    'Reduced running costs',
    'Modern, reliable technology',
    'Extended warranty coverage'
  ];

  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);

  benefits.forEach(benefit => {
    yPos = checkPageBreak(doc, yPos, 15, margin);
    yPos = addWrappedText(doc, `✓ ${benefit}`, margin + 3, yPos, contentWidth - 3, 5);
    yPos += 6;
  });

  addPageFooter(doc, pageNum);
}

/**
 * Generate product recommendations page with photos
 */
async function generateProductRecommendationsPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Product & Service Recommendations', pageNum, totalPages);

  let yPos = 35;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Based on your requirements, we recommend the following products:', margin, yPos);
  yPos += 12;

  // Products from database query or materials list
  const products = summaryData.products || [];

  for (const product of products) {
    yPos = checkPageBreak(doc, yPos, 80, margin);

    // Product name
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(102, 126, 234);
    doc.text(product.name, margin, yPos);
    yPos += 8;

    // Product image if available
    if (product.imageUrl) {
      try {
        const imageData = await loadImageAsBase64(product.imageUrl);
        if (imageData) {
          const imgWidth = 40;
          const imgHeight = 30;
          doc.addImage(imageData, 'PNG', margin, yPos, imgWidth, imgHeight);

          // Description next to image
          doc.setFontSize(9);
          doc.setFont(undefined, 'normal');
          doc.setTextColor(0, 0, 0);
          const descX = margin + imgWidth + 5;
          const descWidth = contentWidth - imgWidth - 5;
          addWrappedText(doc, product.description || '', descX, yPos + 5, descWidth, 5);

          yPos += imgHeight + 5;
        }
      } catch (error) {
        console.error('Failed to load product image:', error);
      }
    } else {
      // Description without image
      doc.setFontSize(9);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(0, 0, 0);
      yPos = addWrappedText(doc, product.description || '', margin, yPos, contentWidth, 5);
      yPos += 5;
    }

    // Why it suits the customer
    if (product.suitabilityReason) {
      doc.setFontSize(8);
      doc.setFont(undefined, 'italic');
      doc.setTextColor(100, 116, 139);
      yPos = addWrappedText(doc, `💡 ${product.suitabilityReason}`, margin, yPos, contentWidth, 4);
      yPos += 3;
    }

    yPos += 8;
  }

  // Fallback if no products specified
  if (products.length === 0) {
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text('Specific product recommendations will be provided following technical assessment.', margin, yPos);
  }

  addPageFooter(doc, pageNum);
}

/**
 * Generate technical specifications page
 */
async function generateTechnicalSpecsPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Technical Specifications', pageNum, totalPages);

  let yPos = 35;

  // Technical specs from database
  const technicalSpecs = summaryData.technicalSpecs || {};

  if (Object.keys(technicalSpecs).length > 0) {
    // Create a table-like layout
    doc.setFillColor(241, 245, 249); // Light gray header
    doc.rect(margin, yPos, contentWidth, 10, 'F');

    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(71, 85, 105);
    doc.text('Specification', margin + 3, yPos + 7);
    doc.text('Details', margin + (contentWidth / 2), yPos + 7);

    yPos += 12;

    // Zebra striping for specs
    let rowIndex = 0;
    for (const [key, value] of Object.entries(technicalSpecs)) {
      yPos = checkPageBreak(doc, yPos, 15, margin);

      if (rowIndex % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, yPos - 5, contentWidth, 8, 'F');
      }

      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text(key, margin + 3, yPos);

      doc.setFont(undefined, 'normal');
      const valueLines = doc.splitTextToSize(value.toString(), (contentWidth / 2) - 10);
      doc.text(valueLines[0], margin + (contentWidth / 2) + 3, yPos);

      yPos += 8;
      rowIndex++;
    }
  } else {
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text('Technical specifications will be confirmed during detailed site survey.', margin, yPos);
  }

  addPageFooter(doc, pageNum);
}

/**
 * Generate warranty table page (British Gas format)
 */
async function generateWarrantyPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Warranty & HomeCare Coverage', pageNum, totalPages);

  let yPos = 35;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Your new system includes comprehensive warranty coverage:', margin, yPos);
  yPos += 12;

  // Warranty table structure (British Gas style)
  const warranties = [
    { level: 'Essential Cover', years: '2', boiler: '✓', controls: '✓', parts: '✓', labor: '✓', annual: '£15/mo' },
    { level: 'Standard Cover', years: '5', boiler: '✓', controls: '✓', parts: '✓', labor: '✓', annual: '£25/mo' },
    { level: 'Premium Cover', years: '10', boiler: '✓', controls: '✓', parts: '✓', labor: '✓', annual: '£35/mo' },
    { level: 'Total Care', years: '12', boiler: '✓', controls: '✓', parts: '✓', labor: '✓', annual: '£45/mo' }
  ];

  // Table header
  const colWidths = {
    level: contentWidth * 0.25,
    years: contentWidth * 0.12,
    boiler: contentWidth * 0.12,
    controls: contentWidth * 0.13,
    parts: contentWidth * 0.12,
    labor: contentWidth * 0.12,
    annual: contentWidth * 0.14
  };

  doc.setFillColor(102, 126, 234); // Purple
  doc.rect(margin, yPos, contentWidth, 10, 'F');

  doc.setFontSize(8);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(255, 255, 255);

  let xPos = margin + 2;
  doc.text('Cover Level', xPos, yPos + 6);
  xPos += colWidths.level;
  doc.text('Years', xPos, yPos + 6);
  xPos += colWidths.years;
  doc.text('Boiler', xPos, yPos + 6);
  xPos += colWidths.boiler;
  doc.text('Controls', xPos, yPos + 6);
  xPos += colWidths.controls;
  doc.text('Parts', xPos, yPos + 6);
  xPos += colWidths.parts;
  doc.text('Labor', xPos, yPos + 6);
  xPos += colWidths.labor;
  doc.text('Monthly', xPos, yPos + 6);

  yPos += 12;

  // Table rows
  doc.setFont(undefined, 'normal');
  doc.setFontSize(8);

  warranties.forEach((warranty, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, yPos - 4, contentWidth, 8, 'F');
    }

    doc.setTextColor(0, 0, 0);
    xPos = margin + 2;

    doc.setFont(undefined, 'bold');
    doc.text(warranty.level, xPos, yPos);
    doc.setFont(undefined, 'normal');

    xPos += colWidths.level;
    doc.text(warranty.years, xPos, yPos);
    xPos += colWidths.years;
    doc.text(warranty.boiler, xPos, yPos);
    xPos += colWidths.boiler;
    doc.text(warranty.controls, xPos, yPos);
    xPos += colWidths.controls;
    doc.text(warranty.parts, xPos, yPos);
    xPos += colWidths.parts;
    doc.text(warranty.labor, xPos, yPos);
    xPos += colWidths.labor;
    doc.setTextColor(16, 185, 129);
    doc.text(warranty.annual, xPos, yPos);
    doc.setTextColor(0, 0, 0);

    yPos += 8;
  });

  yPos += 10;

  // Info box
  doc.setFillColor(209, 250, 229); // Light green
  doc.roundedRect(margin, yPos, contentWidth, 20, 3, 3, 'F');

  doc.setFontSize(8);
  doc.setFont(undefined, 'italic');
  doc.setTextColor(0, 0, 0);
  const infoText = 'All warranty levels include annual boiler service, 24/7 emergency helpline, and unlimited callouts for covered repairs. HomeCare cover can be added to extend protection beyond the manufacturer warranty period.';
  addWrappedText(doc, infoText, margin + 5, yPos + 6, contentWidth - 10, 4);

  addPageFooter(doc, pageNum);
}

/**
 * Generate pricing breakdown page
 */
async function generatePricingPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Pricing Breakdown', pageNum, totalPages);

  let yPos = 35;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Estimated costs for the proposed system:', margin, yPos);
  yPos += 15;

  // Pricing items
  const pricingItems = summaryData.pricingItems || [];

  // Table header
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, yPos, contentWidth, 10, 'F');

  doc.setFontSize(9);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Item Description', margin + 3, yPos + 7);
  doc.text('Price', pageWidth - margin - 30, yPos + 7);

  yPos += 12;

  // Items
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  let subtotal = 0;

  pricingItems.forEach((item, idx) => {
    yPos = checkPageBreak(doc, yPos, 15, margin);

    if (idx % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, yPos - 5, contentWidth, 8, 'F');
    }

    doc.setFontSize(9);
    const descLines = doc.splitTextToSize(item.description, contentWidth - 40);
    doc.text(descLines[0], margin + 3, yPos);

    doc.setFont(undefined, 'bold');
    doc.text(`£${item.price.toFixed(2)}`, pageWidth - margin - 30, yPos, { align: 'right' });
    doc.setFont(undefined, 'normal');

    subtotal += item.price;
    yPos += 8;
  });

  // Totals
  yPos += 5;
  const totalsX = pageWidth - margin - 60;

  doc.setDrawColor(102, 126, 234);
  doc.setLineWidth(0.5);
  doc.rect(totalsX - 5, yPos - 5, 65, 35);

  doc.setFontSize(10);
  doc.text('Subtotal:', totalsX, yPos);
  doc.setFont(undefined, 'bold');
  doc.text(`£${subtotal.toFixed(2)}`, totalsX + 45, yPos, { align: 'right' });

  yPos += 7;
  doc.setFont(undefined, 'normal');
  const vatAmount = subtotal * 0.2;
  doc.text('VAT (20%):', totalsX, yPos);
  doc.setFont(undefined, 'bold');
  doc.text(`£${vatAmount.toFixed(2)}`, totalsX + 45, yPos, { align: 'right' });

  yPos += 10;
  const total = subtotal + vatAmount;
  doc.setFillColor(102, 126, 234);
  doc.rect(totalsX - 5, yPos - 7, 65, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('Total:', totalsX, yPos);
  doc.text(`£${total.toFixed(2)}`, totalsX + 45, yPos, { align: 'right' });

  addPageFooter(doc, pageNum);
}

/**
 * Calculate finance payment
 */
function calculateFinancePayment(principal, months, apr = 0) {
  if (apr === 0) {
    return principal / months;
  }

  const monthlyRate = apr / 100 / 12;
  const payment = (principal * monthlyRate * Math.pow(1 + monthlyRate, months)) /
                  (Math.pow(1 + monthlyRate, months) - 1);
  return payment;
}

/**
 * Generate finance calculator page
 */
async function generateFinancePage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Finance Options', pageNum, totalPages);

  let yPos = 35;

  const totalPrice = summaryData.totalPrice || 5000;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Flexible payment options to suit your budget:', margin, yPos);
  yPos += 15;

  // Finance options
  const financeOptions = [
    { term: 24, apr: 0, label: '24 months interest-free' },
    { term: 36, apr: 0, label: '36 months interest-free' },
    { term: 60, apr: 9.9, label: '60 months at 9.9% APR' },
    { term: 120, apr: 9.9, label: '120 months at 9.9% APR' }
  ];

  financeOptions.forEach((option, idx) => {
    yPos = checkPageBreak(doc, yPos, 40, margin);

    const monthlyPayment = calculateFinancePayment(totalPrice, option.term, option.apr);
    const totalRepayable = monthlyPayment * option.term;
    const totalInterest = totalRepayable - totalPrice;

    // Option box
    doc.setFillColor(idx < 2 ? 209 : 241, idx < 2 ? 250 : 245, idx < 2 ? 229 : 249);
    doc.roundedRect(margin, yPos, contentWidth, 30, 3, 3, 'F');

    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(102, 126, 234);
    doc.text(option.label, margin + 5, yPos + 8);

    doc.setFontSize(16);
    doc.setTextColor(16, 185, 129);
    doc.text(`£${monthlyPayment.toFixed(2)}/month`, margin + 5, yPos + 20);

    doc.setFontSize(8);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Total repayable: £${totalRepayable.toFixed(2)}`, pageWidth - margin - 60, yPos + 12);
    if (totalInterest > 0) {
      doc.text(`Interest: £${totalInterest.toFixed(2)}`, pageWidth - margin - 60, yPos + 18);
    } else {
      doc.setTextColor(16, 185, 129);
      doc.text('No interest charged', pageWidth - margin - 60, yPos + 18);
    }

    yPos += 35;
  });

  // Finance note
  yPos += 5;
  doc.setFontSize(7);
  doc.setFont(undefined, 'italic');
  doc.setTextColor(100, 116, 139);
  const financeNote = 'Finance subject to status and approval. Representative APR shown. Monthly payments calculated on outstanding balance. Terms and conditions apply. Finance provided by authorized credit brokers.';
  addWrappedText(doc, financeNote, margin, yPos, contentWidth, 3);

  addPageFooter(doc, pageNum);
}

/**
 * Generate HomeCare savings calculator page
 */
async function generateHomeCareSavingsPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'HomeCare Savings Calculator', pageNum, totalPages);

  let yPos = 35;

  const currentAnnualCost = summaryData.currentHomeCareCost || 300;
  const proposedMonthlyCost = summaryData.proposedHomeCareCost || 25;
  const proposedAnnualCost = proposedMonthlyCost * 12;
  const annualSaving = currentAnnualCost - proposedAnnualCost;
  const fiveYearSaving = annualSaving * 5;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Compare your current HomeCare costs with our comprehensive cover:', margin, yPos);
  yPos += 15;

  // Current vs Proposed comparison
  const colWidth = (contentWidth - 10) / 2;

  // Current cost box
  doc.setFillColor(254, 243, 199); // Light yellow
  doc.roundedRect(margin, yPos, colWidth, 45, 3, 3, 'F');

  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(146, 64, 14);
  doc.text('Current HomeCare', margin + 5, yPos + 10);

  doc.setFontSize(20);
  doc.setTextColor(239, 68, 68);
  doc.text(`£${currentAnnualCost}`, margin + 5, yPos + 28);

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text('per year', margin + 5, yPos + 38);

  // Proposed cost box
  doc.setFillColor(209, 250, 229); // Light green
  doc.roundedRect(margin + colWidth + 10, yPos, colWidth, 45, 3, 3, 'F');

  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(16, 185, 129);
  doc.text('With New System', margin + colWidth + 15, yPos + 10);

  doc.setFontSize(20);
  doc.text(`£${proposedAnnualCost}`, margin + colWidth + 15, yPos + 28);

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text('per year', margin + colWidth + 15, yPos + 38);

  yPos += 55;

  // Savings summary
  doc.setFillColor(102, 126, 234); // Purple
  doc.roundedRect(margin, yPos, contentWidth, 50, 3, 3, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('💰 Your Savings', margin + 5, yPos + 12);

  doc.setFontSize(14);
  doc.text(`£${annualSaving.toFixed(0)} per year`, margin + 5, yPos + 25);

  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text(`Over 5 years: £${fiveYearSaving.toFixed(0)}`, margin + 5, yPos + 38);

  yPos += 60;

  // What's included
  yPos = checkPageBreak(doc, yPos, 60, margin);

  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(102, 126, 234);
  doc.text('What\'s Included in Your Cover:', margin, yPos);
  yPos += 8;

  const includedItems = [
    'Annual boiler service and safety check',
    'Unlimited emergency callouts (24/7)',
    'All parts and labor covered',
    'Central heating system repairs',
    'Controls and thermostat coverage',
    'Gas safety inspections',
    'No excess charges on callouts'
  ];

  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);

  includedItems.forEach(item => {
    yPos = checkPageBreak(doc, yPos, 10, margin);
    doc.text(`✓ ${item}`, margin + 3, yPos);
    yPos += 6;
  });

  addPageFooter(doc, pageNum);
}

/**
 * Generate terms and conditions page
 */
async function generateTermsPage(doc, summaryData, pageNum, totalPages) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  addPageHeader(doc, 'Terms & Conditions', pageNum, totalPages);

  let yPos = 35;

  const termsText = summaryData.termsAndConditions || getDefaultTerms();

  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(0, 0, 0);

  yPos = addWrappedText(doc, termsText, margin, yPos, contentWidth, 4);

  addPageFooter(doc, pageNum);
}

/**
 * Default terms and conditions
 */
function getDefaultTerms() {
  return `INFORMATION SUMMARY DISCLAIMER: This document is provided for informational purposes only and does not constitute a formal quotation, contract, offer, or guarantee of service. All information contained herein is subject to verification, site survey, and final confirmation.

PRICING: All prices shown are estimates based on initial assessment and are subject to change. Final pricing will be confirmed following detailed site survey. Prices include VAT at the current rate unless otherwise stated. Additional costs may apply for unforeseen works, structural modifications, or complications discovered during installation.

TECHNICAL SPECIFICATIONS: Product specifications and technical details are provided as general guidance only. Actual specifications may vary based on manufacturer availability, site requirements, and current regulations. All installations will comply with current Building Regulations, Gas Safe requirements, and manufacturer guidelines.

FINANCE OPTIONS: Finance options shown are for illustration purposes only and are subject to credit approval and status. APR rates and terms are indicative and may vary. Finance is provided by authorized credit brokers. Terms and conditions apply.

WARRANTY COVERAGE: Warranty levels and HomeCare cover options are subject to terms and conditions of the relevant warranty provider. Annual service visits and ongoing maintenance requirements must be met to maintain warranty validity. Exclusions and limitations apply.

SITE SURVEY: A detailed site survey will be required before any work commences. The survey may identify additional works required, access limitations, or other factors that may affect final pricing and installation timeline.

TIMELINE: Installation timelines are estimates only and subject to survey completion, product availability, weather conditions, and scheduling. We will endeavor to provide accurate timelines following survey completion.

ACCEPTANCE: No contract exists until a formal written quotation has been provided, accepted in writing by the customer, and a deposit has been paid. This information summary does not bind either party to any agreement or obligation.

MODIFICATIONS: We reserve the right to modify or withdraw this information summary at any time. Any subsequent formal quotation will supersede this document.

PROPERTY ACCESS: Customer is responsible for ensuring clear access to all work areas and for protecting furnishings and belongings. Any access restrictions must be communicated prior to survey or installation.

BUILDING CONTROL: Where required, Building Control notifications and certifications will be arranged. Additional fees may apply. Customer is responsible for ensuring any necessary permissions or consents are obtained.

GENERAL: This information summary is governed by English law. All rights reserved. For questions or clarifications, please contact us directly.`;
}

/**
 * Main PDF generation function
 * @param {Object} summaryData - All data needed for the PDF
 * @returns {Promise<string>} - Filename of generated PDF
 */
export async function generateComprehensiveSummaryPDF(summaryData) {
  // Wait for jsPDF to load
  if (typeof window.jspdf === 'undefined') {
    throw new Error('jsPDF library not loaded. Please ensure jsPDF is included in your HTML.');
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  // Estimate total pages (will be updated as we generate)
  const estimatedPages = 12;
  let currentPage = 1;

  try {
    // Page 1: Cover page
    await generateCoverPage(doc, summaryData);
    currentPage++;

    // Page 2: Existing system analysis
    doc.addPage();
    await generateExistingSystemPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 3: Proposed system
    doc.addPage();
    await generateProposedSystemPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 4: Product recommendations
    doc.addPage();
    await generateProductRecommendationsPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 5: Technical specifications
    doc.addPage();
    await generateTechnicalSpecsPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 6: Warranty table
    doc.addPage();
    await generateWarrantyPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 7: Pricing breakdown
    doc.addPage();
    await generatePricingPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 8: Finance calculator
    doc.addPage();
    await generateFinancePage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 9: HomeCare savings
    doc.addPage();
    await generateHomeCareSavingsPage(doc, summaryData, currentPage, estimatedPages);
    currentPage++;

    // Page 10: Terms & Conditions
    doc.addPage();
    await generateTermsPage(doc, summaryData, currentPage, estimatedPages);

    // Generate filename
    const sessionName = summaryData.sessionName || 'Session';
    const date = new Date().toISOString().split('T')[0];
    const safeSessionName = sessionName.replace(/[^a-zA-Z0-9]/g, '_');
    const filename = `summary-${safeSessionName}-${date}.pdf`;

    // Save the PDF
    doc.save(filename);

    return filename;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  }
}

/**
 * Preview PDF in new tab (without downloading)
 */
export async function previewComprehensiveSummaryPDF(summaryData) {
  if (typeof window.jspdf === 'undefined') {
    throw new Error('jsPDF library not loaded');
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  // Generate all pages (same as generateComprehensiveSummaryPDF but without saving)
  const estimatedPages = 12;
  let currentPage = 1;

  await generateCoverPage(doc, summaryData);
  currentPage++;

  doc.addPage();
  await generateExistingSystemPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateProposedSystemPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateProductRecommendationsPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateTechnicalSpecsPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateWarrantyPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generatePricingPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateFinancePage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateHomeCareSavingsPage(doc, summaryData, currentPage, estimatedPages);
  currentPage++;

  doc.addPage();
  await generateTermsPage(doc, summaryData, currentPage, estimatedPages);

  // Open in new tab
  const pdfBlob = doc.output('blob');
  const pdfUrl = URL.createObjectURL(pdfBlob);
  window.open(pdfUrl, '_blank');
}
